(cl:defpackage beginner_tutorials-srv
  (:use )
  (:export
   "ADDTWOINTS"
   "<ADDTWOINTS-REQUEST>"
   "ADDTWOINTS-REQUEST"
   "<ADDTWOINTS-RESPONSE>"
   "ADDTWOINTS-RESPONSE"
   "BATIMENTOS"
   "<BATIMENTOS-REQUEST>"
   "BATIMENTOS-REQUEST"
   "<BATIMENTOS-RESPONSE>"
   "BATIMENTOS-RESPONSE"
   "MULTTWOINTS"
   "<MULTTWOINTS-REQUEST>"
   "MULTTWOINTS-REQUEST"
   "<MULTTWOINTS-RESPONSE>"
   "MULTTWOINTS-RESPONSE"
   "SENSOR"
   "<SENSOR-REQUEST>"
   "SENSOR-REQUEST"
   "<SENSOR-RESPONSE>"
   "SENSOR-RESPONSE"
  ))

