// Generated by gencpp from file beginner_tutorials/Batimentos.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_BATIMENTOS_H
#define BEGINNER_TUTORIALS_MESSAGE_BATIMENTOS_H

#include <ros/service_traits.h>


#include <beginner_tutorials/BatimentosRequest.h>
#include <beginner_tutorials/BatimentosResponse.h>


namespace beginner_tutorials
{

struct Batimentos
{

typedef BatimentosRequest Request;
typedef BatimentosResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Batimentos
} // namespace beginner_tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::beginner_tutorials::Batimentos > {
  static const char* value()
  {
    return "0cd2157d7eaac1ba7a7e9dde0a510aef";
  }

  static const char* value(const ::beginner_tutorials::Batimentos&) { return value(); }
};

template<>
struct DataType< ::beginner_tutorials::Batimentos > {
  static const char* value()
  {
    return "beginner_tutorials/Batimentos";
  }

  static const char* value(const ::beginner_tutorials::Batimentos&) { return value(); }
};


// service_traits::MD5Sum< ::beginner_tutorials::BatimentosRequest> should match 
// service_traits::MD5Sum< ::beginner_tutorials::Batimentos > 
template<>
struct MD5Sum< ::beginner_tutorials::BatimentosRequest>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::Batimentos >::value();
  }
  static const char* value(const ::beginner_tutorials::BatimentosRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::BatimentosRequest> should match 
// service_traits::DataType< ::beginner_tutorials::Batimentos > 
template<>
struct DataType< ::beginner_tutorials::BatimentosRequest>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::Batimentos >::value();
  }
  static const char* value(const ::beginner_tutorials::BatimentosRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::beginner_tutorials::BatimentosResponse> should match 
// service_traits::MD5Sum< ::beginner_tutorials::Batimentos > 
template<>
struct MD5Sum< ::beginner_tutorials::BatimentosResponse>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::Batimentos >::value();
  }
  static const char* value(const ::beginner_tutorials::BatimentosResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::BatimentosResponse> should match 
// service_traits::DataType< ::beginner_tutorials::Batimentos > 
template<>
struct DataType< ::beginner_tutorials::BatimentosResponse>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::Batimentos >::value();
  }
  static const char* value(const ::beginner_tutorials::BatimentosResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_BATIMENTOS_H
