// Generated by gencpp from file beginner_tutorials/Sensor.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_SENSOR_H
#define BEGINNER_TUTORIALS_MESSAGE_SENSOR_H

#include <ros/service_traits.h>


#include <beginner_tutorials/SensorRequest.h>
#include <beginner_tutorials/SensorResponse.h>


namespace beginner_tutorials
{

struct Sensor
{

typedef SensorRequest Request;
typedef SensorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Sensor
} // namespace beginner_tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::beginner_tutorials::Sensor > {
  static const char* value()
  {
    return "0cd2157d7eaac1ba7a7e9dde0a510aef";
  }

  static const char* value(const ::beginner_tutorials::Sensor&) { return value(); }
};

template<>
struct DataType< ::beginner_tutorials::Sensor > {
  static const char* value()
  {
    return "beginner_tutorials/Sensor";
  }

  static const char* value(const ::beginner_tutorials::Sensor&) { return value(); }
};


// service_traits::MD5Sum< ::beginner_tutorials::SensorRequest> should match 
// service_traits::MD5Sum< ::beginner_tutorials::Sensor > 
template<>
struct MD5Sum< ::beginner_tutorials::SensorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::Sensor >::value();
  }
  static const char* value(const ::beginner_tutorials::SensorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::SensorRequest> should match 
// service_traits::DataType< ::beginner_tutorials::Sensor > 
template<>
struct DataType< ::beginner_tutorials::SensorRequest>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::Sensor >::value();
  }
  static const char* value(const ::beginner_tutorials::SensorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::beginner_tutorials::SensorResponse> should match 
// service_traits::MD5Sum< ::beginner_tutorials::Sensor > 
template<>
struct MD5Sum< ::beginner_tutorials::SensorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::Sensor >::value();
  }
  static const char* value(const ::beginner_tutorials::SensorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::SensorResponse> should match 
// service_traits::DataType< ::beginner_tutorials::Sensor > 
template<>
struct DataType< ::beginner_tutorials::SensorResponse>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::Sensor >::value();
  }
  static const char* value(const ::beginner_tutorials::SensorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_SENSOR_H
